Ddhub dev file upload
energywebfoundation/dsb-client-gateway pull request #101
Opened 2022-02-15 18:32 UTC by vikaskumr

2022-02-16 08:22 UTC, kim-energyweb requested changes
I think we should use Dev Env of Message Broker for .dev config and use Azam's for .local config

2022-02-16 08:22 UTC, kim-energyweb commented on .env.development
> +DSB_BASE_URL=https://aemovc.eastus.cloudapp.azure.com
https://ddhub-dev.energyweb.org/

2022-02-19 12:25 UTC, vikaskumr commented on data/in-memory.json
> +{
there is a reason why this folder is not in .gitignore as we are using this folder for Kubernetes volume

2022-02-24 12:55 UTC, hejkerooo approved these changes

2022-02-25 05:44 UTC, merged