Ddhub dev topic management
energywebfoundation/dsb-client-gateway pull request #108
Opened 2022-03-16 06:47 UTC by vikaskumr

2022-03-16 08:36 UTC, hejkerooo requested changes

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +            Authorization: `Bearer ${this.authToken}`,
Don't use this.authToken, use `Authorization: `Bearer ${this.didAuthService.getToken()}`,`

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +            Authorization: `Bearer ${this.authToken}`,
as above

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +        this.logger.error(e);
why not rethrow this error? either return null in that case and update method definition or rethrow this error

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +      const data = await this.iamService.getApplicationsByOwner(ownerDid)
```suggestion
      return this.iamService.getApplicationsByOwner(ownerDid)
```

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +  public async getApplicationsByOwner(ownerDid: string): Promise<Array<IApp>> {
Why this method is in dsb api service while it's IAM context?

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/dsb-client.interface.ts
> +export type ApplicationDTO = {
Why type? I strongly prefer to use `interface` for such cases, check the below link about it. 

https://stackoverflow.com/a/63579488

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-frontend/src/components/ProxyCertificate/ProxyCertificate.tsx
> +                  accept=".pem, .der, .cer"
why remove .crt?
>The certificate file types can be .pem, .crt, .cer, or .key. 

https://www.tutorialsteacher.com/https/ssl-certificate-format

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-frontend/src/pages/applications/index.tsx
> +const applicationsData = [
shouldn't be removed?

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-frontend/src/pages/applications/index.tsx
> +    // useEffect(() => {
why this code is commented out?

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-frontend/src/pages/topicdialog/index.tsx
> +let schemaTypes = [
why `let` ?

2022-03-16 08:36 UTC, hejkerooo commented on apps/dsb-client-gateway-frontend/src/services/dsb-api.service.ts
> +      const res = await this.api.get('https://aemovc.eastus.cloudapp.azure.com/topic', {
You can't call message broker directly from frontend, every request should be proxied by backend

2022-03-16 12:55 UTC, hejkerooo commented
Also please follow semantic commits structure

2022-03-21 04:47 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +            Authorization: `Bearer ${this.authToken}`,
done

2022-03-21 04:47 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +            Authorization: `Bearer ${this.authToken}`,
done

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/dsb-client.interface.ts
> +export type Result<T = boolean, E = GatewayError> = {
I don't like this approach - it's an attempt to replace `try/catch` and it's going to introduce a lot of complexity in backend. Please remove it

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/dto/index.ts
> +  @IsString()
Apply DID validation (did pipe)

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/dto/index.ts
> +  @IsNotEmpty()
Apply `@ArrayUnique`, `@IsString` 


please add swagger definitions like `ApiProperty`

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/iam-service/service/iam.service.ts
> +      if (didClaim.claimType.startsWith('topiccreator') && didClaim.namespace !== 'message.broker.app.namespace') {
`'message.broker.app.namespace'` -> move it to env. variable or some constant

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/dsb-client.interface.ts
> +export type ApplicationHeader = {
use interface instead of type

2022-03-22 08:20 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/controller/dsb-topics.controller.ts
> +  public async getTopics() {
add more swagger docs

2022-03-22 08:21 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/controller/dsb-applications.controller.ts
> +        const applications = await this.iamService.getApplicationsByOwner(ownerDid);
move it to some service and probably this controller should be in some sort `iam.controller.ts`

2022-03-22 08:22 UTC, hejkerooo requested changes
Looks good in overall, just couple small changes

2022-03-22 08:35 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +const qs = require('qs');
use import instead of require

2022-03-22 16:45 UTC, hejkerooo approved these changes

2022-03-22 16:51 UTC, merged