feat: update enrolment flow
energywebfoundation/dsb-client-gateway pull request #134
Opened 2022-03-31 15:24 UTC by hejkerooo

2022-04-01 12:22 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/module/did-auth/service/did-auth.service.ts
> +        console.log('attempt', attempt);
can we remove console.logs

2022-04-01 12:51 UTC, vikaskumr requested changes

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +    ) {
can we throw e.return message also as we recieve it from message broker

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +      return retry();
if it is unauthorized  will it stops after certain retry if not then API will stuck

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +          stopOnResponseCodes: ['10'],
what is return code 10 mean can we make it in const.ts file

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/enrolment/enrolment.module.ts
> +  imports: [UtilsModule, StorageModule, forwardRef(() => IdentityModule)],
can you please tell me why do we need forwardRef here

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/enrolment/service/enrolment.service.ts
> +    const enrolment: Enrolment | null = this.enrolmentRepository.getEnrolment();
await ?

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/identity/identity.controller.ts
> +  })
can we get type also?

2022-04-01 12:51 UTC, vikaskumr commented on apps/dsb-client-gateway-api/src/app/modules/identity/service/identity.service.ts
> +      this.getIdentity(true),
can we catch the errors thrown by Promise.all

2022-04-01 12:53 UTC, vikaskumr commented
Backend build is also failing because of tests

2022-04-02 21:17 UTC, dawidgil commented on apps/dsb-client-gateway-api/src/app/modules/identity/service/identity.service.ts
> +        return RoleState.APPROVED;
Can you move this enum to library so frontend can reuse it as well?

2022-04-02 21:17 UTC, dawidgil commented on apps/dsb-client-gateway-api/src/app/modules/identity/identity.interface.ts
> +export interface IdentityWithEnrolment {
Please move those interfaces into library. It might be called `identity-types` or something similar.

2022-04-02 21:29 UTC, dawidgil commented on apps/dsb-client-gateway-api/src/app/modules/enrolment/service/enrolment.service.ts
> +          waiting: false,
I see `waiting` means the same what `RoleState.AWAITING_APPROVAL`. Do we need this duplication? I'm just curious.

2022-04-03 14:31 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/enrolment/enrolment.module.ts
> +  imports: [UtilsModule, StorageModule, forwardRef(() => IdentityModule)],
because of circular dependency - enrolment module uses identity service while identity service is using enrolment service

2022-04-03 14:31 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/enrolment/service/enrolment.service.ts
> +    const enrolment: Enrolment | null = this.enrolmentRepository.getEnrolment();
no need to do it

2022-04-04 05:54 UTC, vikaskumr approved these changes
Please do all the changes in the next PR

2022-04-04 07:07 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +    ) {
we throw whole error so it's included

2022-04-04 07:08 UTC, hejkerooo commented on apps/dsb-client-gateway-api/src/app/modules/dsb-client/service/dsb-api.service.ts
> +          stopOnResponseCodes: ['10'],
we need to get list of errors from Azam to create map of errors

2022-04-04 08:24 UTC, merged