Dsb client verify signature
energywebfoundation/dsb-client-gateway pull request #16
Opened 2021-08-26 06:02 UTC by vikaskumr

2021-08-30 12:45 UTC, yartman requested changes

2021-08-30 12:45 UTC, yartman commented on src/pages/api/v1/verifysignature/index.ts
> +    if (!req.body.signature || !req.body.did || !req.body.payload) {
i think it needs to be checked if those are strings also

2021-08-30 12:45 UTC, yartman commented on src/pages/api/v1/verifysignature/index.ts
> +    try {
there is no need for trycatch block here since ethers doesn't throw errors

2021-09-01 10:04 UTC, vikaskumr commented on src/pages/api/v1/verifysignature/index.ts
> +    try {
in this case ethers is throwing error if signature is not valid

2021-09-01 10:43 UTC, yartman approved these changes

2021-09-01 10:51 UTC, merged