Dsb client sentry intergration
energywebfoundation/dsb-client-gateway pull request #20
Opened 2021-09-03 04:39 UTC by vikaskumr

sentry integration

2021-09-03 04:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/energywebfoundation/dsb-client-gateway?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/energywebfoundation/dsb-client-gateway?pullRequest=20) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vikaskumr<br/>:x: Vikas Kumar<br/><hr/>**Vikas Kumar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/energywebfoundation/dsb-client-gateway?pullRequest=20) it.</sub>

2021-09-13 07:33 UTC, adamstaveley requested changes
See comments. It's also missing documentation. Please add all the relevant environment variables to `CONFIGURATION.md` and add a section in `README.md` about how to set this up.

2021-09-13 07:33 UTC, adamstaveley commented on .env.development
> +SENTRY_CLI_EXECUTABLE=../../.npm/_npx/777/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
Why do we need a CLI? Does that mean all users who opt-in to using sentry must install the CLI? Furthermore, this looks like a relative import to global installation of the CLI, which may not be the same for other users. You should put this in `.env.local`.

2021-09-13 07:33 UTC, adamstaveley commented on .env.development
> +SENTRY_AUTH_TOKEN=42e9f22d8c114b3393810f4aec8976219277343acaee468a8abbb929d4bac954
If this is the auth token used to send logs to our energyweb sentry project, please don't hardcode it. Better that we give it to users only if they request it (opt-in). If you are able to generate a new token and invalidate this one, please do, because this is now public.

2021-09-13 07:33 UTC, adamstaveley commented on .env.production
> +SENTRY_CLI_EXECUTABLE=../../.npm/_npx/777/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
same as .development

2021-09-13 07:33 UTC, adamstaveley commented on _next.config.js
> +// This file sets a custom webpack configuration to use your Next.js app
delete this file

2021-09-13 07:33 UTC, adamstaveley commented on sentry.client.config.js
> +  dsn: SENTRY_DSN || 'https://9baea420fdd34148b27363b41f646da9@o517012.ingest.sentry.io/5938887',
what is this hardcoded dsn?

2021-09-13 07:33 UTC, adamstaveley commented on src/pages/api/v1/channels/index.ts
> +export default handler
missing `withSentry` I think

2021-09-13 07:33 UTC, adamstaveley commented on src/pages/api/v1/config/enrol.ts
> +            captureException(Error(ErrorCode.ID_NO_PRIVATE_KEY))
these exceptions are handled and will also be logged as a message in the catch block, so I think you can remove

2021-09-13 07:33 UTC, adamstaveley commented on src/pages/files/index.tsx
> +import * as Sentry from "@sentry/nextjs"
unused

2021-09-13 09:49 UTC, vikaskumr commented on .env.development
> +SENTRY_AUTH_TOKEN=42e9f22d8c114b3393810f4aec8976219277343acaee468a8abbb929d4bac954
removed the public token

2021-09-15 14:33 UTC, adamstaveley requested changes

2021-09-15 14:33 UTC, adamstaveley commented on .gitignore
> +.sentryclirc
Think you only need this once!

2021-09-15 14:33 UTC, adamstaveley commented on Dockerfile
> +#RUN export SENTRY_CLI=./node_modules/.bin/sentry-cli
so just to be clear, no source maps in this version?

2021-09-15 14:33 UTC, adamstaveley commented on README.md
> +-e SENTRY_URL=<SENTRY_URL> -e NEXT_PUBLIC_SENTRY_ENABLED=true -e SENTRY_ORG=<SENTRY_ORG> -e SENTRY_PROJECT=<SENTRY_PROJECT> -e NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>
`SENTRY_URL|ORG|PROJECT` are already set. The user should only need to provide `-e NEXT_PUBLIC_SENTRY_ENABLED=true -e NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>`

2021-09-15 14:33 UTC, adamstaveley commented on README.md
> +### Install
make it `####`

2021-09-15 14:33 UTC, adamstaveley commented on README.md
> +### Configure
delete this section - Sentry is already configured

2021-09-15 14:33 UTC, adamstaveley commented on sentry.properties
> +defaults.url=process.env.SENTRY_URL
why is this file needed?

2021-09-15 14:33 UTC, adamstaveley commented on src/components/GatewayIdentity/GatewayIdentityContainer.tsx
> +import * as Sentry from "@sentry/nextjs"
unused - does simply loading it into a component make it active?

2021-09-15 14:33 UTC, adamstaveley commented on CONFIGURATION.md
> +### `SENTRY` [optional]
Change to `## Sentry`

2021-09-15 14:33 UTC, adamstaveley commented on CONFIGURATION.md
> +For every partner different sentry url will be same as while doing setup it opens this link on browser to confirm the authentication
didn't understand that

2021-09-15 14:33 UTC, adamstaveley commented on CONFIGURATION.md
> +For every partner different sentry url will be same as while doing setup it opens this link on browser to confirm the authentication
it's optional - can you provide the default value, also for the vars below? see other sections for how to format it

2021-09-15 14:33 UTC, adamstaveley commented on README.md
> +-e SENTRY_URL=<SENTRY_URL> -e NEXT_PUBLIC_SENTRY_ENABLED=true -e SENTRY_ORG=<SENTRY_ORG> -e SENTRY_PROJECT=<SENTRY_PROJECT> -e NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>
as discussed, set `NEXT_PUBLIC_SENTRY_ENABLE=true`, then we only need `-e NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>`

2021-09-15 14:37 UTC, vikaskumr commented on .gitignore
> +.sentryclirc
yes it is actually done by npm so I have uninstalled and installed it again so it might have been written 3 times will correct it

2021-09-15 14:39 UTC, vikaskumr commented on src/components/GatewayIdentity/GatewayIdentityContainer.tsx
> +import * as Sentry from "@sentry/nextjs"
no no it is useless will remove it

2021-09-15 14:52 UTC, vikaskumr commented on CONFIGURATION.md
> +For every partner different sentry url will be same as while doing setup it opens this link on browser to confirm the authentication
done given default values

2021-09-15 14:53 UTC, vikaskumr commented on README.md
> +-e SENTRY_URL=<SENTRY_URL> -e NEXT_PUBLIC_SENTRY_ENABLED=true -e SENTRY_ORG=<SENTRY_ORG> -e SENTRY_PROJECT=<SENTRY_PROJECT> -e NEXT_PUBLIC_SENTRY_DSN=<SENTRY_DSN>
done

2021-09-15 14:54 UTC, vikaskumr commented on CONFIGURATION.md
> +### `SENTRY` [optional]
done

2021-09-15 14:55 UTC, vikaskumr commented on README.md
> +### Install
done

2021-09-15 14:58 UTC, vikaskumr commented on README.md
> +### Configure
done

2021-09-15 15:07 UTC, vikaskumr commented on sentry.properties
> +defaults.url=process.env.SENTRY_URL
there are 2 ways to configure these values so we can do it directly using the environment variables so deleting this file

2021-09-15 15:39 UTC, vikaskumr commented on Dockerfile
> +#RUN export SENTRY_CLI=./node_modules/.bin/sentry-cli
no currently no source map version but as written in documentation stack trace will be available in captureException which we have used

2021-09-16 07:39 UTC, adamstaveley requested changes
Looking better. Just some small things and it still needs the unused imports removed.

2021-09-16 07:39 UTC, adamstaveley commented on CONFIGURATION.md
> +## `SENTRY` [optional]
This a heading. It does not need to be monospace. You can also remove [optional] as that tag is for the actual environment variables. So: `## Sentry`

2021-09-16 07:39 UTC, adamstaveley commented on README.md
> +### Sentry [optional]
remove [optional]

2021-09-16 09:53 UTC, vikaskumr commented on CONFIGURATION.md
> +## `SENTRY` [optional]
done

2021-09-16 09:53 UTC, vikaskumr commented on README.md
> +### Sentry [optional]
done

2021-09-16 12:08 UTC, adamstaveley approved these changes

2021-09-16 12:09 UTC, merged